services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: stream-pulse-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16-alpine
    container_name: stream-pulse-postgres
    environment:
      POSTGRES_USER: stream_pulse
      POSTGRES_PASSWORD: stream_pulse
      POSTGRES_DB: stream_pulse
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U stream_pulse -d stream_pulse']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ingester:
    build:
      context: ./ingester
    container_name: stream-pulse-ingester
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      PORT: 3000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: wikimedia
      RABBITMQ_QUEUE: wikimedia.recentchange
      RABBITMQ_ROUTING_KEY: recentchange
    ports:
      - '3000:3000'
    restart: unless-stopped

  aggregator:
    build:
      context: ./aggregator
    container_name: stream-pulse-aggregator
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: wikimedia
      RABBITMQ_RAW_QUEUE: wikimedia.recentchange
      RABBITMQ_RAW_ROUTING_KEY: recentchange
      RABBITMQ_PROCESSED_QUEUE: wikimedia.recentchange.processed
      RABBITMQ_PROCESSED_ROUTING_KEY: recentchange.processed
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: stream_pulse
      POSTGRES_PASSWORD: stream_pulse
      POSTGRES_DB: stream_pulse
      TYPEORM_SYNCHRONIZE: 'true'
    ports:
      - '3001:3001'
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres_data:
